# Generated by Django 5.2 on 2026-08-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='information',
            field=models.CharField(blank=True, max_length=500, verbose_name='Информация'),
        ),
    ]
